version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lees-test-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ztlobt4dlgdb"
s3_prefix = "lees-test-sam-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
