AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  step functions

Resources:
  NQueensStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/nqueens.asl.json
      DefinitionSubstitutions:
        MakeInputFunctionArn: !GetAtt MakeInputFunction.Arn
        RunNQueensFunctionArn: !GetAtt RunNQueensFunction.Arn
      Events:
        HourlyQueens:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Description: Schedule to run the state machine every hour
            Enabled: False
            Schedule: "rate(1 hour)"
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref MakeInputFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RunNQueensFunction

  MakeInputFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: mkinput
      Runtime: go1.x
      Environment:
        Variables:
          S3_OUTPUT_BUCKET: !Ref InputBucket

  RunNQueensFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/nqueens/
      Handler: nqueens
      Runtime: go1.x
  
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lees-stepper-input
  
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lees-stepper-output

  SrcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lees-stepper-src

# Outputs:
#   # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
#   # Find out more about other implicit resources you can reference within SAM
#   # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
#   StockTradingStateMachineArn:
#     Description: "Stock Trading State machine ARN"
#     Value: !Ref StockTradingStateMachine
#   StockTradingStateMachineRoleArn:
#     Description: "IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates"
#     Value: !GetAtt StockTradingStateMachineRole.Arn
